config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :products do
    resources :orders
  end

  resources :users do
    resources :orders, only: %i[index destroy]
  end



  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :product

  validates :quantity, presence: true, numericality: {
    greater_than: 0,
    less_than_or_equal_to: ->(order) { order.product.quantity },
    message: "deve ser maior que 0 e não ultrapassar o estoque"
  }
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  has_many_attached :photos

  validates :quantity, numericality: { greater_than: 0, message: "deve ser maior que 0" }
  validates :price, numericality: { greater_than: 0, message: "deve ser maior que 0" }

  include PgSearch::Model
  pg_search_scope :search_by_name_category_and_description,
  against: [:name, :category, :description],
  using: {
    tsearch: { prefix: true }
  }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :products
  has_many :orders
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_params, if: :devise_controller?

  protected

  def configure_permitted_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :address, :birthdate, :email, :password])
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_products, only: [:new, :create]

  def index
    @order = Order.all
  end

  def show
    @order = Order.find(params[:id])
  end

  def new
    @order = Order.new
  end

  def create
    @order = Order.new(quantity: params["quantity"])
    @order.user = current_user
    @order.product = @product
    if @order.save
      redirect_to product_order_path(@product, @order), notice: 'the order was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    order = Order.find(params[:id])
    if order.destroy
      redirect_to user_orders_path(current_user), notice: 'the order was successfully destroyed.'
    else
      redirect_to user_orders_path(current_user), notice: 'A ordem de compra não foi excluída'
    end
  end

  private

  def order_params
    params.require(:order).permit(:quantity)
  end

  def set_products
    @product = Product.find(params[:product_id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @products = Product.all

    if params[:query].present?
      @products = @products.search_by_name_category_and_description(params[:query])
    end

    if params[:category].present?
      @products = @products.where(category: params[:category])
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    @product.user = current_user
    if @product.save
      redirect_to product_path(@product), notice: 'the product was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @product = Product.find(params[:id])
    if @product.user == current_user
      @product.destroy
      redirect_to products_path, notice: "Produto excluído com sucesso."
    else
      redirect_to products_path, alert: "Você não tem permissão para excluir este produto."
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    @product.update(product_params)
    # No need for app/views/tasks/update.html.erb
    redirect_to product_path(@product)
  end

  def destroy
    @product = Product.find(params[:id])
    if @product.destroy
      redirect_to root_path, notice: "Produto excluído com sucesso."
    else
      redirect_to root_path, alert: "Ocorreu um erro ao excluir o seu produto!"
    end
  end

  private

  def product_params
    params.require(:product).permit(:name, :description, :category, :price, :quantity, photos: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Escolare</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <!--- <p class="notice"><%= notice %></p> --->
    <!--- <p class="alert"><%= alert %></p> --->
      <%= yield %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/orders/index.html.erb
<div class="bg-sessions">
  <div class="container py-5">
    <div class="row">
      <div class="col-12 col-md-6 offset-lg-3">
        <div class="bg-white rounded p-3 shadow">

        <h1 class="text-center">Compras Recentes:</h1>

        <ul>
          <% @order.each_with_index do |order, index| %>

          <div class="card-product m-4 d-flex justify-content-between">
              <%= image_tag order.product.photos[0] %>

              <div class="card-product-infos ">
                <h2><%= order.product.name %></h2>
                <p>Quantidade: <%= order.quantity %></p>
                <p>Valor unitário: <%= number_to_currency(order.product.price) %></p>
                <p>Valor total: <%= number_to_currency(order.product.price * order.product.quantity) %></p>
              </div>

            <!-- <div class="d-flex justify-content-end"> -->
              <%= link_to user_order_path(order.user.id, order),
                title: "Clique aqui para excluir esta compra da sua lista",
                data: {turbo_method: :delete, turbo_confirm: "Tem certeza que deseja excluir?"} do %>
                <button class="btn btn-primary text-white font-bold me-4"><i class="fa-solid fa-trash"></i> Excluir</button>
              <% end %>
            <!-- </div> -->

          </div>
        <% end %>
      </ul>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/orders/myorders.html.erb
<div class="bg-sessions">
<div class="container py-5">

  <div class="row">

    <div class="col-12 col-md-6 offset-lg-3">

      <div class="bg-white rounded p-3 shadow">
      <h1>Veja abaixo sua compra, <%= @user.name %></h1>
      <ul>
      <% @orders.each do |order| %>
      <li><%= order.product.name %> - Quantity: <%= order.quantity %></li>
      <% end %>
      </ul>

      </div>
    </div>
  </div>
</div>
</div>

app/views/orders/new.html.erb
<div class="bg-sessions">
  <div class="container py-5">

      <div class="bg-white rounded p-3 shadow">

        <div class="row-one">

          <h2>Efetue a Compra</h2>
          <p>Preencha a quantidade desejada do produto</p>

        </div>

        <div class="row-two d-flex justify-content-evenly">

          <%= image_tag @product.photos[0] %>

          <div class="product_info d-flex flex-column justify-content-evenly">

            <h4><%= @product.name %></h4>


            <p>Estoque: <%=@product.quantity%></p>


            <h3 class="card-trip-pricing">R$<%= @product.price %></h3>

          </div>

          <%= simple_form_for [@product, @order] do |f| %>
            <%= f.input :quantity, label: "Quantidade" %>
            <%= f.button :submit, "Comprar", class: "btn btn-primary ml-auto text-white font-weight-bold" %>
          <% end %>

        </div>


      </div>

  </div>

</div>

app/views/orders/show.html.erb
<div class="container py-3">

  <div class="bg-white rounded p-3 shadow">
    <div class="row no_margin">

      <!-- Nome do produto, Categoria, Estoque e Redes sociais -->
      <div class="col-lg-12 column_infos d-flex flex-column justify-content-center">
        <div class="col-12 p-2 name">

          <h2>A sua compra de <%=@order.product.name.capitalize %> está a caminho!</h2>
      </div>
      </div>

      <div class="col-lg-12 column_img d-flex justify-content-center">
        <div class="card-trip col-8 d-flex justify-content-center shadow-none">
        <%= image_tag 'order-on-going.png'%>
          </div>
        </div>

            <div class="col-lg-12 column_infos d-flex flex-column justify-content-center">
        <div class="col-12 p-2">

          <h3>Será enviado para o endereço:</h3>
          <p><%=current_user.address %></p>

        <div class="text-end">
        <%= link_to user_orders_path(@order), title: "Minhas Compras" do %>
        <button class="btn btn-primary text-white font-bold">Minhas Compras</button>
        <% end %>
        </div>

      </div>

      </div>
      </div>


      </div>
    </div>
  </div>

  <!-- Parte de descrição do produto -->

</div>

app/views/pages/home.html.erb
<!-- Início do carousel-->
<div id="carouselExample" class="carousel slide">

  <div class="carousel-inner">
    <div class="carousel-item active">
      <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1629652487043-fb2825838f8c?q=80&w=2071&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D);">

        <div class="container">
          <h1>Compre e venda seus <strong>materiais escolares</strong> aqui!<strong></strong></h1>
          <p></p>
          <%= link_to new_product_path do %>
            <button class="btn btn-primary ml-auto text-white font-weight-bold">Adicione seu produto aqui <i class="fa-solid fa-plus"></i> </button>
          <% end %>
        </div>

      </div>
    </div>

    <div class="carousel-item">
      <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1452860606245-08befc0ff44b?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D);">
          <div class="container">
            <h1>Do pré ao <strong>ensino basico!</strong><strong></strong></h1>
            <p></p>
            <a class="btn btn-primary ml-auto text-white font-weight-bold" href="#">Veja nossas promoções</a>
          </div>
      </div>
    </div>

    <div class="carousel-item">
      <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1456735190827-d1262f71b8a3?q=80&w=2048&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D);">
        <div class="container">
          <h1>Materiais para <strong>festinhas e eventos</strong> você tambem pode encontrar ou vender aqui! <strong></strong></h1>
          <p></p>
          <a class="btn btn-primary ml-auto text-white font-weight-bold" href="#">Veja nossas promoções</a>
        </div>
      </div>
    </div>

  </div>

  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>

  <button class="carousel-control-next" type="button" data-bs-target="#carouselExample" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>

</div><!-- Fim do carousel-->

<div class="selection-categories pb-2 mb-3 pt-3">
  <div class="container">
    <ul class="list-inline tabs-underlined">
      <!-- Array para armazenar as categorias -->
      <% prodCat = ["Artes", "Aventais", "Brinquedos", "Esteiras", "Eventos", "Lancheiras", "Livraria", "Mochilas", "Papelaria"]%>
      <li>
        <%= link_to root_path, class: (params[:category].blank? ? "tab-underlined active" : "tab-underlined") do %>
          <i class="fa-solid fa-border-all"></i>
        <% end %>
      </li>
      <% prodCat.each do |categ| %>
        <li>
          <%= link_to categ, root_path(category: categ), class: (params[:category] == categ ? "tab-underlined active" : "tab-underlined") %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

<div class="container py-5 d-none">
  <div class="row">
    <% @products.each do |product|%>
      <%= link_to product_path(product), class:"text-decoration-none" do %>
        <div class="card-category">
          <p><%= product.name %></p>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

<div class="cards container">

  <!-- Para cada produto é criado um card -->
  <% @products.each_with_index do |product, index| %>
    <div class="card-trip col m-1">

      <!-- A div inteira do produto será clicável -->
      <%= link_to product_path(product), class: "text-decoration-none" do %>
        <!-- Início Carousel imagem Produtos -->
        <div id="carouselExample2<%= index %>" class="carousel slide">
          <div class="carousel-inner">
            <% product.photos.each_with_index do |photo, photo_index| %>
              <div class="carousel-item <%= 'active' if photo_index.zero? %>">
                <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= cl_image_path photo.key, height: 300, width: 400, crop: :fill %>);">
                </div>
              </div>
            <% end %>
          </div>

          <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample2<%= index %>" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
          </button>

          <button class="carousel-control-next" type="button" data-bs-target="#carouselExample2<%= index %>" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
          </button>
        </div> <!-- Fim Carousel imagem Produtos -->

        <!-- Nome, descrição e preço do produto -->
        <div class="card-trip-infos">
          <div>
            <h2><%= product.name %></h2>
            <p><%= truncate(product.description, length: 35, omission: '...') %></p>
          </div>
          <h2 class="card-trip-pricing">R$<%= product.price %></h2>
        </div>

      <% end %> <!-- Fechamento do link_to -->
    </div>
  <% end %> <!-- Fechamento da iteração dos produtos -->
</div>

app/views/products/edit.html.erb
<div class="bg-sessions">
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">
        <h3>Edite seu Produto</h3>
        <%= simple_form_for @product do |f| %>
          <%= f.input :name, label: "Nome do Produto", input_html: { value: @product.name } %>
          <%= f.input :category, selected: @product.category, collection: ['Artes', 'Aventais', 'Brinquedos', 'Esteiras', 'Eventos', 'Lancheira', 'Livraria', 'Mochilas', 'Papelaria'], label: "Categoria" %>
          <%= f.input :description, label: "Descrição", input_html: { value: @product.description } %>
          <%= f.input :quantity, label: "Quantidade", input_html: { value: @product.quantity } %>
          <%= f.input :price, label: "Preço", input_html: { value: @product.quantity }%>
          <div class="d-flex justify-content-center">
            <%= f.button :submit, "Editar Produto" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
</div>

app/views/products/new.html.erb
<div class="bg-sessions">>
<div class="container py-5">

  <div class="row">

    <div class="col-12 col-md-6 offset-lg-3 mb-10">

      <div class="bg-white rounded p-3 shadow">
        <h3>Oferte seu produto aqui:</h3>
        <%= simple_form_for @product do |f| %>
          <%= f.input :name, label: "Nome do Produto" %>
          <%= f.input :category, collection: ['Artes', 'Aventais', 'Brinquedos', 'Esteiras', 'Eventos', 'Lancheira', 'Livraria', 'Mochilas', 'Papelaria'], label: "Categoria" %>
          <%= f.input :description, label: "Descrição" %>
          <%= f.input :quantity,label: "Quantidade" %>
          <%= f.input :price, label: "Preço" %>
          <%= f.input :photos, as: :file, input_html: { multiple: true }, label: "Adicionar imagem do produto" %>
          <div class="d-flex justify-content-center">
            <%= f.button :submit, "Criar Produto", class: "btn btn-primary ml-auto text-white font-weight-bold" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
</div>

app/views/products/show.html.erb
<div class="container py-3">

  <div class="d-flex justify-content-end gap-3 mb-3">

    <!-- Botões de editar, excluir e criar mais produtos aparecem caso o usuário seja
    o mesmo que criou o produto visualizado -->

    <% if @product.user === current_user  %>

      <div class="text-end">
        <%= link_to edit_product_path(@product), title: "Clique aqui para editar o produto" do %>
          <button class="btn btn-primary text-white font-bold"><i class="fa-solid fa-pen"></i> Editar Produto</button>
        <% end %>
      </div>

      <div class="text-center">
        <%= link_to product_path(@product),
          data: {turbo_method: :delete, turbo_confirm: "Tem certeza que deseja excluir?"} do %>
          <button class="btn btn-primary text-white font-bold"><i class="fa-solid fa-trash"></i> Excluir Produto</button>
        <% end %>
      </div>

      <div class="text-end">
        <%= link_to new_product_path, title: "Clique aqui para criar um novo produto" do %>
          <button class="btn btn-primary text-white font-bold"><i class="fa-solid fa-plus"></i> Criar Produto</button>
        <% end %>
      </div>

    <% end %>
  </div>

  <div class="bg-white rounded p-3 shadow">
    <div class="row no_margin">

      <!-- Nome do produto, Categoria, Estoque e Redes sociais -->
      <div class="col-lg-6 column_infos d-flex flex-column justify-content-between">
        <div class="col-12 p-2 name">

          <h1><%= @product.name.capitalize %></h1>

          <p>Categoria:<%= @product.category.capitalize %></p>

          <div class="text-share">Disponíveis:<b><%= @product.quantity %></b></div>

          <div class="d-flex align-items-center justify-content-end">
            <p class="text-share my-2">Compartilhe:</p>
            <button class="button-social"><i class="fa-brands fa-square-facebook"></i></button>
            <button class="button-social"><i class="fa-brands fa-square-instagram"></i></button>
            <button class="button-social"><i class="fa-brands fa-square-x-twitter"></i></button>
            <button class="button-social"><i class="fa-brands fa-square-pinterest"></i></button>
          </div>
        </div>


        <!-- Preço e Formulário de compra -->
        <div class="col-12 p-2 bar_price d-flex justify-content-end">
          <div class="row d-flex flex-row-reverse">

              <div class="col-sm-6 text-price d-flex justify-content-end">R$<b><%= @product.price %></b></div>

              <div class="row d-flex flex-row-reverse">
                <div class="col-sm-6 text-end">
                  <%= form_tag product_orders_path(@product) do %>
                    <div class="input-group">
                      <%= number_field_tag :quantity, 1, class: "form-control" %>
                      <button type="submit" class="btn btn-primary text-white font-bold">Compre Agora</button>
                    </div>
                  <% end %>
                </div>
              </div>

          </div>
        </div>
      </div>

      <div class="col-lg-6 column_img">
        <div class="card-trip col-12">

          <!-- Início do Carousel de imagem do produto-->
          <div id="carouselExample2" class="carousel slide">

            <div class="carousel-inner">
              <% @product.photos.each_with_index do |photo, photo_index| %>
                <div class="carousel-item <%= 'active' if photo_index.zero? %>">
                  <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.2)), url(<%= cl_image_path photo.key, height: 200, width: 300, crop: :fill %>);">
                  </div>
                </div>
              <% end %>
            </div>

            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample2" data-bs-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Previous</span>
            </button>

            <button class="carousel-control-next" type="button" data-bs-target="#carouselExample2" data-bs-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Next</span>
            </button>

          </div><!-- Final do Carousel de imagem do produto-->
        </div>
      </div>
    </div>
  </div>

  <!-- Parte de descrição do produto -->
  <div class="bg-white rounded p-3 shadow border-top">
    <h2>Descrição:</h2>
    <%= @product.description.capitalize %>
  </div>

</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="d-flex flex-column body">

    <!-- FOOTER -->
    <footer class="w-100 py-4 flex-shrink-0">
        <div class="container py-4">
            <div class="row gy-4 gx-5">
                <div class="col-lg-4 col-md-6">
                    <h1 class="display-4 text-white">Escolare</h1>
                    <p class="small text-white">Oferecemos uma ampla seleção de produtos escolares de qualidade, entregues diretamente à sua porta!</p>
                    <p class="small mb-0 text-white">&copy; Copyrights. All rights reserved.</p>
                </div>
                <div class="col-lg-2 col-md-6">
                    <h5 class="text-white mb-3">Quick links</h5>
                    <ul class="list-unstyled text-white">
                        <li><a href="#">Home</a></li>
                        <li><a href="#">Login</a></li>
                        <li><a href="#">Venda seus produtos</a></li>
                    </ul>
                </div>

                <div class="col-lg-2 col-md-6">
                    <h5 class="text-white mb-3">Redes Sociais</h5>
                    <div class="d-flex align-items-center">
                      <button class="button-social text-white"><i class="fa-brands fa-square-facebook"></i></button>
                      <button class="button-social text-white"><i class="fa-brands fa-square-instagram"></i></button>
                      <button class="button-social text-white"><i class="fa-brands fa-square-x-twitter"></i></button>
                      <button class="button-social text-white"><i class="fa-brands fa-square-pinterest"></i></button>
                    </div>
                </div>

                <div class="col-lg-4 col-md-6 d-flex justify-content-evenly">
                        <%= link_to root_path, class: "navbar-brand" do %>
                          <%= image_tag "logo.png", class: "img-logo-footer" %>
                        <% end %>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logo.png", class: "img-logo" %>
      <%= image_tag "logoname.png", class: "name-logo" %>
    <% end %>

    <%#= simple_form_for :search, url: root_path, method: :get do |f| %>
  <%# <div class="search-form-control form-group">
    <input class="form-control string required" type="text" name="search[query]" id="search_query" />
    <button name="button" type="submit" class="btn btn-flat">
      <i class="fas fa-search"></i>
    </button>
  </div> %>
<%# end %>

    <%= form_with url: root_path, method: :get, class: "search-form-control form-group" do %>
      <%= text_field_tag :query,
            params[:query],
            class: "form-control string required",
            placeholder: "Buscar Produtos"
        %>
      <%= button_tag(type: 'submit', class: "btn btn-flat") do %>
        <i class="fas fa-search"></i>
      <% end %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to root_path, class: "nav-link" do %>
            <i class="fa-solid fa-house"></i>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to "#", class: "nav-link" do %>
            <i class="fa-solid fa-envelope"></i>
            <i class="fa-solid"></i>
            <% end %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://static-00.iconduck.com/assets.00/profile-circle-icon-1023x1024-ucnnjrj1.png", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Venda", new_product_path, class: "dropdown-item" %>
              <%= link_to "Minhas Compras", user_orders_path(current_user), class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item btn btn-primary text-white font-weight-bold">
            <%= link_to "Login", new_user_session_path, class: "nav-link btn btn-primary text-white" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>